Add support for preview frame time code
bennord/appstore-tools pull request #9
Opened 2021-04-27 14:20 UTC by luke14free

This PR introduces two features:

(1) validation of the uploaded app previews and removal of "FAILED" uploaded assets (thus preventing things such as those describe in #7 to happen in the frontend)
(2) setting of the preview time code to either: `00:00:00:01` or the value of the `<preview_name_without_extension>.txt`. Note that this is an opinionated choice, as the app store by default uses the value at `00:00:05:01` which to me is quite non-sensical

2021-04-27 14:34 UTC, luke14free commented
I have also added an allow list for videos which is mp4, mov, avi (nothing else should be supported by App Store Connect)

2021-04-27 15:31 UTC, luke14free commented
And ".jpg", ".jpeg", ".png", ".tif", ".tiff", ".bmp" for images (I know it's outside of the scope once again.. sorry)

2021-04-29 08:40 UTC, bennord commented
Just fyi, on holiday for a week, so I'll be a bit slow to respond. I'll take a look at the PRs soon as I get back.

2021-05-05 15:51 UTC, luke14free commented
oh no worries!! enjoy! :D

2021-05-10 07:23 UTC, bennord requested changes
Back from break, and getting caught up on stuff.  Sorry for the long wait for these comments!

2021-05-10 07:23 UTC, bennord commented on appstore_tools/actions/publish.py
> +    _, screenshot_ext = os.path.splitext(file_name)
Let's not hard-code the extensions into `publish_screenshot`.  Instead, let's leave it as an option (with our list as the default set from the command-line).

My proposal for implmentation:
- Leave `publish_screenshot` unchanged.  If the callers tell this function to publish a path, it does it, no complaints.
- Add a parameter to `publish_screenshots` for the extension filter list.  Callers can use this if they want to filter by extension.
- Add an option to the command-line args, with the list used here as the default value.  This let's users of the command-line program override if needed via args or the config file that works with all command-line args.

2021-05-10 07:23 UTC, bennord commented on appstore_tools/actions/publish.py
> +    preview_frame_time_code_filepath = os.path.join(
In the case that we need to add other configurable values per preview file in the future, let's decide if each would be in their own file or all in one file as named values.

Option 1:
- example.avi
- example_preview_frame_time_code.txt
- example_some_future_option.txt

Option 2:
- example.avi
- example.txt
  ```
  # contents of example.txt
  preview_frame_time_code=00:00:00:01
  some_future_option=true
  ```

2021-05-10 07:27 UTC, bennord commented on appstore_tools/actions/publish.py
> +    preview_frame_time_code_filepath = os.path.join(
I probably lean more towards option 2.

2022-11-04 14:33 UTC, bennord commented on appstore_tools/actions/publish.py
> +    _, screenshot_ext = os.path.splitext(file_name)
can now use `--asset-ignore` if you have non video files you need to ignore https://github.com/bennord/appstore-tools/pull/13

2022-11-04 14:34 UTC, bennord commented on .gitignore
> +.DS_Store
Thanks!  This has been added now https://github.com/bennord/appstore-tools/pull/14

2022-11-05 15:32 UTC, bennord commented
https://github.com/bennord/appstore-tools/pull/16 addresses the previewFrameTimeCode feature.

2022-11-05 15:34 UTC, bennord commented
Let me know if there's anything missing still form this PR that hasn't been addressed and we can reopen something if needed.

2022-11-05 15:34 UTC, closed without merging